---
# Common variables for all environments
backup_retention_days: 30
backup_storage_type: "standard"
backup_compression: true

# Environment configuration
cloud_provider: "azure"  # Options: "azure" or "oci"
environment: "dev"       # Options: "dev", "staging", "prod"
resource_prefix: "elt"
vpc_cidr: "10.0.0.0/16"
subnet_count: 3

# Test variables with interpolation
test_resource_name: "{{ resource_prefix }}-{{ environment }}-test"
test_complex_name: "{{ resource_prefix }}-{{ environment }}-{{ cloud_provider }}-test"
test_number: "{{ subnet_count + 1 }}"

# Azure configuration
azure_location: "eastus"
azure_resource_group: "cloud-elt-{{ environment }}"
azure_storage_account: "cloudelt{{ environment }}"
azure_container_name: "backups"

# Azure resource configuration
storage_tier: "Standard_LRS"
databricks_sku: "premium"
vm_size: "Standard_B1s"

# Azure resource names
azure_resource_group_name: "{{ resource_prefix }}-{{ environment }}-rg"
azure_storage_account_name: "{{ resource_prefix }}{{ environment }}sa"
azure_virtual_network_name: "{{ resource_prefix }}-{{ environment }}-vnet"
azure_subnet_name: "{{ resource_prefix }}-{{ environment }}-subnet"
azure_vm_name: "{{ resource_prefix }}-{{ environment }}-vm"
azure_vm_os_disk_size_gb: 30
azure_vm_admin_username: "adminuser"

# Azure storage configuration
azure_storage_account_tier: "Standard"
azure_storage_min_tls_version: "TLS1_2"
azure_storage_container_access_type: "private"

# OCI configuration
oci_compartment_name: "cloud-elt-{{ environment }}"
oci_bucket_name: "cloud-elt-backups-{{ environment }}"
oci_namespace: "{{ lookup('env', 'OCI_NAMESPACE') }}"

# OCI resource configuration
oci_region: "eu-stockholm-1"      # Updated to match your OCI CLI config
compute_shape: "VM.Standard.E2.1.Micro"  # Always Free eligible shape
oci_compartment_id: "ocid1.tenancy.oc1..aaaaaaaawcczb6nidnd6rfoqmbvqg6dihslqsrrgnw6kysz6yix4lcvig2va"  # Using root compartment until a specific one is created

# OCI resource names
oci_vcn_name: "{{ resource_prefix }}-{{ environment }}-vcn"
oci_subnet_name: "{{ resource_prefix }}-{{ environment }}-subnet"
oci_instance_name: "{{ resource_prefix }}-{{ environment }}-instance"
oci_instance_ocpus: 1
oci_instance_memory_in_gbs: 1
oci_instance_os: "Oracle Linux"
oci_instance_os_version: "8"

# OCI storage configuration
oci_storage_tier: "Standard"
oci_storage_versioning: "Enabled"
oci_storage_auto_tiering: "Enabled"
oci_storage_lifecycle_days: 30

# OCI compute configuration
oci_compute_ocpus: 1
oci_compute_memory_gb: 1

# Databricks configuration
databricks_docker_port: 8443
databricks_docker_image: "databricks/community-edition"

# Path configurations
oci_private_key_path: "~/.oci/oci_api_key.pem"
ssh_private_key_path: "~/.ssh/id_rsa"
ssh_public_key_path: "~/.ssh/id_rsa.pub"

# Monitoring configuration
log_retention_days: 30
alert_email_addresses: "jan.ahlin@gmail.com"
