---
- name: Install OCI CLI
  pip:
    name: oci-cli
    state: present

- name: Create .oci directory
  file:
    path: "/home/{{ ansible_user }}/.oci"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Template OCI config file
  template:
    src: oci_config.j2
    dest: "/home/{{ ansible_user }}/.oci/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Generate OCI API key pair
  shell: |
    openssl genrsa -out ~/.oci/oci_api_key.pem 2048
    chmod 600 ~/.oci/oci_api_key.pem
    openssl rsa -pubout -in ~/.oci/oci_api_key.pem -out ~/.oci/oci_api_key_public.pem
  args:
    creates: "/home/{{ ansible_user }}/.oci/oci_api_key.pem"
  become: yes
  become_user: "{{ ansible_user }}"
