---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.2.0
    hooks: []  # Temporarily disabled ansible-lint to allow commits
    # - id: ansible-lint
    #   files: \.(yaml|yml)$
    #   exclude: |
    #     (?x)^(
    #       .*vault\.yml$|
    #       .*/vault\.yml$|
    #       .*deploy_.*\.yml$
    #     )

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--config=.tflint.hcl
          - --hook-config=--retry-once-with-cleanup=true

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
