---
all:
  children:
    controller:
      hosts:
        controller-vm:
          ansible_host: <CONTROLLER_VM_IP>
          ansible_user: azureuser
  vars:
    ansible_connection: ssh
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    cloud_provider: azure