---
all:
  children:
    controller:
      hosts:
        controller-vm:
          ansible_connection: local
          ansible_host: localhost
          ansible_user: "{{ lookup('env', 'USER') }}"
  vars:
    cloud_provider: azure
    environment: development
