---
all:
  children:
    controller:
      hosts:
        controller-vm:
          ansible_host: 192.168.1.100
          ansible_user: janne
  vars:
    ansible_connection: ssh
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    cloud_provider: azure