---
# Common role tasks

- name: Ensure common packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - unzip
    - jq
  when: ansible_system == "Linux"
  become: true
  ignore_errors: true

- name: Install common dependencies
  ansible.builtin.package:
    name:
      - git
      - python3-pip
    state: present

- name: Create workspace directory
  ansible.builtin.file:
    path: "{{ workspace_dir | default('/opt/cloud-elt-infra') }}"
    state: directory
    mode: '0755'

- name: Clone cloud-elt-infra repository
  ansible.builtin.git:
    repo: "https://github.com/mock/cloud-elt-infra.git"
    dest: "{{ workspace_dir | default('/opt/cloud-elt-infra') }}"
    version: "main"
