---
- name: Ensure common packages are installed
  ansible.builtin.package:
    name:
      - curl
      - wget
      - unzip
      - jq
    state: present
  when: ansible_system == "Linux"
  become: true
  ignore_errors: true

- name: Install common dependencies
  ansible.builtin.package:
    name:
      - git
      - python3-pip
    state: present

- name: Ensure workspace directory exists
  ansible.builtin.file:
    path: "{{ workspace_dir | default('/opt/cloud-elt-infra') }}"
    state: directory
    mode: '0755'
  when: workspace_dir is defined and workspace_dir != ansible_env.PWD
