# Example hosts file for Ansible inventory
# -------------------------------------
# This file defines the controller VM where Ansible will run.
# Copy this file to ansible/inventories/<environment>/hosts.yml and update the values.

all:
  hosts:
    controller:  # This is the VM where Ansible will run
      ansible_host: "192.168.1.100"  # IP address of your controller VM
      ansible_user: "ansible"         # SSH user for connecting to the controller
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"  # Path to your SSH private key
      # Optional: If using password authentication instead of SSH key
      # ansible_ssh_pass: "your-ssh-password"
      # ansible_become: true  # If sudo access is needed
      # ansible_become_pass: "your-sudo-password" 