---
# Playbook to check infrastructure status
- name: Check infrastructure status
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    is_check_mode: true
  tasks:
    - name: Run terraform state list
      ansible.builtin.command: terraform state list
      register: terraform_state
      changed_when: false
      failed_when: false

    - name: Display terraform state
      ansible.builtin.debug:
        var: terraform_state.stdout_lines

    - name: Verify key resources exist
      ansible.builtin.command: terraform state show "{{ item }}"
      register: resource_state
      changed_when: false
      loop:
        - "module.networking"
        - "module.compute"
        - "module.storage"
      when: check_mode | bool

    - name: Display resource state
      ansible.builtin.debug:
        var: resource_state.results
      when: check_mode | bool
