---
- name: Setup Controller VM for OCI
  hosts: controller
  become: yes
  vars:
    cloud_provider: "oci"
  # Include vault-encrypted variables
  vars_files:
    - "../group_vars/{{ environment | default('dev') }}/vault.yml"
  roles:
    - common
    - terraform
    - oci_tools
    - python_tools
    - controller_setup

- name: Deploy OCI Infrastructure
  hosts: controller
  become: no  # Run as the ansible_user to use configured credentials
  vars:
    cloud_provider: "oci"
    terraform_dir: "/opt/cloud-elt-infra/terraform"
    environment: "{{ environment | default('dev') }}"
  # Include vault-encrypted variables
  vars_files:
    - "../group_vars/{{ environment | default('dev') }}/vault.yml"
  roles:
    - infrastructure_deploy